DROP TABLE IF EXISTS courses;
CREATE TABLE courses(
	courseId SERIAL PRIMARY KEY NOT NULL,
	code VARCHAR(7) NOT NULL,
	name TEXT NOT NULL,
	professor TEXT,
	program VARCHAR NOT NULL
);
DROP TABLE IF EXISTS students;
CREATE TABLE students(
	studentID SERIAL PRIMARY KEY NOT NULL,
	firstName TEXT NOT NULL,
	lastName TEXT NOT NULL,
	email TEXT UNIQUE NOT NULL,
	phone VARCHAR(10),
	startDate DATE
);